---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: geerlingguy/ubuntu2004
provisioner:
  name: ansible
  playbooks:
    prepare: ./prepare.yaml
    cleanup: ./cleanup.yaml
verifier:
  name: ansible
